when many crawl queues are generated, this NPE can occur; probably
==================================================================

Date: 2015-09-05 14:12:17

``` {style="white-space:pre-wrap;width:81ex"}
when many crawl queues are generated, this NPE can occur; probably
caused as concurrency issue:
W 2015/09/05 14:09:10 ConcurrentLog java.lang.NullPointerException
java.lang.NullPointerException
    at java.util.TreeMap.rotateRight(TreeMap.java:2239)
    at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2271)
    at java.util.TreeMap.put(TreeMap.java:582)
    at net.yacy.kelondro.table.Table.(Table.java:235)
    at net.yacy.crawler.HostQueue.openStack(HostQueue.java:229)
    at net.yacy.crawler.HostQueue.getStack(HostQueue.java:204)
    at net.yacy.crawler.HostQueue.push(HostQueue.java:397)
    at net.yacy.crawler.HostBalancer.push(HostBalancer.java:237)
    at net.yacy.crawler.data.NoticedURL.push(NoticedURL.java:184)
    at net.yacy.crawler.CrawlStacker.stackCrawl(CrawlStacker.java:355)
    at net.yacy.crawler.CrawlStacker.job(CrawlStacker.java:134)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at
net.yacy.kelondro.workflow.InstantBlockingThread.job(InstantBlockingThread.java:101)
    at
net.yacy.kelondro.workflow.AbstractBlockingThread.run(AbstractBlockingThread.java:82)
    at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
